import React from 'react';
import Head from 'next/head';
import styled from '@emotion/styled';

import { Header, mobileBreak, smallBreak, largeBreak } from '../shared/styles';
import Sidebar from './Sidebar';
import HeaderLogo from './HeaderLogo';

export const MainContainer = styled.div`
	width: 100%;
	flex-direction: column;
	margin: 0 auto;
	display: flex;
	justify-content: space-between;
	align-items: flex-start;

	@media (min-width: ${mobileBreak}) {
		width: 750px;
		flex-direction: row;
	}

	@media (min-width: ${smallBreak}) {
		width: 970px;
		flex-direction: row;
	}

	@media (min-width: ${largeBreak}) {
		width: 1170px;
		flex-direction: row;
	}
`;

export const ContentColumn = styled.div`
	width: 95%;
	margin: 0 auto;

	@media (min-width: ${mobileBreak}) {
		width: calc(66% - 4px);
	}
`;

interface Props {
	children: React.ReactNode;
	titlePrefix?: string;
}

export default function PageShell({ children, titlePrefix }: Props) {
	return (
		<>
			<Head>
				<title>{titlePrefix} Blog.</title>
				<meta name="theme-color" content="#808080" />
				<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
				<meta property="og:url" content="https://sha.wn.zone{{ request.get_full_path }}" />
				<meta property="og:locale" content="en_US" />
				<meta property="og:site_name" content="sha.wn.zone" />
				<meta property="fb:app_id" content="2021111818111122" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				{/** TODO: Google analytics, AMP maybe */}
			</Head>
			<Header>
				<HeaderLogo />
			</Header>
			<MainContainer>
				<ContentColumn>{children}</ContentColumn>
				<Sidebar />
			</MainContainer>
		</>
	);
}
