import { GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from '@emotion/styled';

import { getAllPosts } from '../lib/post';

import {
	Header,
	mobileBreak,
	smallBreak,
	largeBreak,
} from '../shared/styles';
import Sidebar from '../components/Sidebar';
import Post from '../components/Post';

export const MainContainer = styled.div`
	width: 100%;
	flex-direction: column;
	margin: 0 auto;
	display: flex;
	justify-content: space-between;
	align-items: flex-start;

	@media (min-width: ${mobileBreak}) {
		width: 750px;
		flex-direction: row;
	}

	@media (min-width: ${smallBreak}) {
		width: 970px;
		flex-direction: row;
	}

	@media (min-width: ${largeBreak}) {
		width: 1170px;
		flex-direction: row;
	}
`;

export const ContentColumn = styled.div`
	width: 95%;
	margin: 0 auto;

	@media (min-width: ${mobileBreak}) {
		width: calc(66% - 4px);
	}
`;

export const getStaticProps = async () => {
	const posts = getAllPosts();

	return {
		props: {
			posts,
		}
	};
};

export default function Home({ posts }: InferGetStaticPropsType<typeof getStaticProps>) {
	return (
		<>
			<Head>
				<title>Blog.</title>
				<meta name="theme-color" content="#808080"/>
				<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1"/>
				<link href='https://fonts.googleapis.com/css?family=Khand:400,600' rel='stylesheet' type='text/css'/>
				<meta property="og:url" content="https://sha.wn.zone{{ request.get_full_path }}" />
				<meta property="og:locale" content="en_US" />
				<meta property="og:site_name" content="sha.wn.zone" />
				<meta property="fb:app_id" content="2021111818111122" />
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
				{/** TODO: Google analytics, AMP maybe */}
			</Head>
			<Header>
				fancy header square thingy goes here
			</Header>
			<MainContainer>
				<ContentColumn>
					{posts.map(post => <Post post={post} isPreview key={post.metadata.title} />)}
				</ContentColumn>
				<Sidebar />
			</MainContainer>
		</>
	);
}
